List data = [
  ["يومًا", "assets/gifs/day.gif"],
  ["أولًا", "assets/gifs/First.gif"],
  ["أكثر", "assets/gifs/more.gif"],
  ["أقل", "assets/gifs/less.gif"],
  ["أيام", "assets/gifs/days.gif"],
  ["إلغاء", "assets/gifs/Cansal.gif"],
  ["اسمي", "assets/gifs/MyName.gif"],
  ["استطيع", "assets/gifs/Ican.gif"],
  ["اسم", "assets/gifs/name.gif"],
  ["اشهر", "assets/gifs/months.gif"],
  ["الحالة", "assets/gifs/status.gif"],
  ["الحالي", "assets/gifs/current.gif"],
  ["الوالدين", "assets/gifs/parents.gif"],
  ["شكرًا", "assets/gifs/thank_you.gif"],
  ["شكوى_بلاغ", "assets/gifs/complaint_notice.gif"],
  ["شهادة", "assets/gifs/dgree.gif"],
  ["شهرا", "assets/gifs/month.gif"],
  ["شوط", "assets/gifs/round.gif"],
  ["صاحب", "assets/gifs/owner.gif"],
  ["صحيحة", "assets/gifs/correct.gif"],
  ["صغير", "assets/gifs/small.gif"],
  ["صفحة", "assets/gifs/page.gif"],
  ["صلاحية", "assets/gifs/validity.gif"],
  ["كيف", "assets/gifs/how.gif"],
  ["لا", "assets/gifs/no.gif"],
  ["لابد من", "assets/gifs/must.gif"],
  ["للإتمام", "assets/gifs/to_complete.gif"],
  ["لاتنطبق", "assets/gifs/don`t_match.gif"],
  ["لاستلام", "assets/gifs/to_receive.gif"],
  ["لإصدار", "assets/gifs/to_issue.gif"],
  ["لانهاء", "assets/gifs/to_finish.gif"],
  ["لايوجد", "assets/gifs/there_is_no.gif"],
  ["لبدء", "assets/gifs/to_start.gif"],
  ["لتجديد", "assets/gifs/to_renew.gif"],
  ["لتحديث", "assets/gifs/to_update.gif"],
  ["لتصحيح", "assets/gifs/to_correct.gif"],
  ["لتفعيل", "assets/gifs/to_activate.gif"],
  ["لتمتلك", "assets/gifs/to_possess.gif"],
  ["لتملك", "assets/gifs/to_own.gif"],
  ["لتوصيل", "assets/gifs/to_deliver.gif"],
  ["لحساب", "assets/gifs/to_account.gif"],
  ["لحسابات", "assets/gifs/to_accounts.gif"],
  ["لحسابك", "assets/gifs/for_your_account.gif"],
  ["لحسابه", "assets/gifs/for_his_account.gif"],
  ["لدي", "assets/gifs/i_have.gif"],
  ["لديه", "assets/gifs/he_has.gif"],
  ["لديهم", "assets/gifs/they_have.gif"],
  ["لذلك", "assets/gifs/therefore.gif"],
  ["لزوجة", "assets/gifs/to_wife.gif"],
  ["لزيارة", "assets/gifs/to_visit.gif"],
  ["لزيارتها", "assets/gifs/to_visit_her.gif"],
  ["لشخص", "assets/gifs/to_someone.gif"],
  ["لشخصين", "assets/gifs/for_two_people.gif"],
  ["لصاحب", "assets/gifs/for_owner.gif"],
  ["لصفحة", "assets/gifs/for_page.gif"],
  ["لعامل", "assets/gifs/for_page.gif"],
  ["لعنوانك", "assets/gifs/to_your_address.gif"],
  [
    "40 ريال عن كل سنة لرخصة القيادة الخاصة",
    "assets/gifs/ 40_SAR_per_year_for_a_private_driving_license.gif"
  ],
  ["100 ريال لكل سنة", "assets/gifs/ 100_SAR_per_year.gif"],
  ["ادارة المركبات ", "assets/gifs/vehicle_management.gif"],
  ["المرور", "assets/gifs/traffic.gif"],
  ["المستفيد", "assets/gifs/beneficiary.gif"],
  [
    "المواطن المقيم المسجل والمفعل في منصة ابشر",
    "assets/gifs/ resident_citizen_registered_and_activated_on_the_absher_platform.gif"
  ],
  ["الوصول الى الخدمة", "assets/gifs/ access_to_the_service.gif"],
  [
    "انا مسرور مساعدك الافتراضي في ابشر",
    "assets/gifs/ i_am_ _masroor_your_virtual_assistant_in_absher.gif"
  ],
  ["تجديد رخصة السير", "assets/gifs/ renewal_of_driving_license.gif"],
  [
    "تجديد رخصة القيادة الخاصة ورخصة قيادة الدراجات النارية فقط",
    "assets/gifs/ renewal_of_private_driving_ license_and_motorcycle_driving_license_only.gif"
  ],
  ["تجديد رخصة القيادة", "assets/gifs/ renewal_of_ driving_license.gif"],
  ["تقييم", "assets/gifs/ assessment.gif"],
  [
    "تمكين الافراد من تجديد رخصة السير للمركبات التي يملكونها",
    "assets/gifs/ enabling_individuals_to_renew_the_driving_license_of_the_vehicles_they_own.gif"
  ],
  [
    "تمكين الافراد من تجديد رخصة قيادة بطريقة الكترونية",
    "assets/gifs/ enabling_individuals_to_renew_a_driver's_ license_electronically.gif"
  ],
  ["جريمة", "assets/gifs/ crime.gif"],
  ["حِرف", "assets/gifs/ crafts.gif"],
  ["خدمات", "assets/gifs/ services.gif"],
  ["خدمات المركبات", "assets/gifs/ automotive_ services.gif"],
  ["خدمات مرورية", "assets/gifs/ traffic_services.gif"],
  ["خدماتي", "assets/gifs/ my_services.gif"],
  ["خلو", "assets/gifs/ emptiness.gif"],
  ["درجات", "assets/gifs/ bicycle.gif"],
  ["دفع", "assets/gifs/pay.gif"],
  ["رابط", "assets/gifs/ link.gif"],
  ["رخصة سلاح", "assets/gifs/ weapon_license.gif"],
  ["رسوم الخدمة", "assets/gifs/ service_fees.gif"],
  [
    "سداد رسوم التجديد ومخالفة التأخير ان وجد",
    "assets/gifs/ payment_of_renewal_fees_and_violation_of_delay_ if_any.gif"
  ],
  ["سريان", "assets/gifs/ validity.gif"],
  ["سعودي", "assets/gifs/ saudi.gif"],
  ["سفارة", "assets/gifs/ embassy.gif"],
  [
    "سيتم ربطك بموظف للإجابة على سؤال",
    "assets/gifs/ you_will_be_linked_to_an_employee_to_answer_a_ question.gif"
  ],
  ["شروط الخدمة", "assets/gifs/ terms_of_service.gif"],
  [
    "شهادة الفحص سارية المفعول",
    "assets/gifs/ valid_ inspection_certificate.gif"
  ],
  ["طباعة", "assets/gifs/ printing.gif"],
  ["عدم", "assets/gifs/ lack.gif"],
  ["عمومي", "assets/gifs/ public.gif"],
  [
    "عن أي فئة تريد الاستفسار",
    "assets/gifs/ which_ category_would_you_like_to_inquire_about.gif"
  ],
  ["عنك", "assets/gifs/ about_you.gif"],
  ["لغة", "assets/gifs/ language.gif"],
  ["لفرد", "assets/gifs/ for_an_individual.gif"],
  ["لقطاع", "assets/gifs/ for_sector.gif"],
  ["لك", "assets/gifs/for_you.gif"],
  ["لكل", "assets/gifs/ for_each.gif"],
  ["لَم", "assets/gifs/ did_not.gif"],
  ["لوحة المعلومات", "assets/gifs/ dashboard.gif"],
  ["مترجم", "assets/gifs/ translator.gif"],
  ["معك", "assets/gifs/ with_you.gif"],
  ["نارية", "assets/gifs/ motorcycles.gif"],
  [
    "وثيقة تأمين سارية على المركبات",
    "assets/gifs/ valid_vehicle_insurance_policy.gif"
  ],
  ["وصف الخدمة", "assets/gifs/ service_ description.gif"],
  [
    "يرجى اختيار المعلومة التي ترغب بمزيد من التفاصيل حولها",
    "assets/gifs/ please_select_the_information_you_ would_like_more_details_about.gif"
  ],
  ["يفتح", "assets/gifs/ opens.gif"],
];
